global:
  postgresql:
    auth:
      postgresPassword: "postgres"
      username: "postgres"
      password: "postgres"
      database: "maindb"

primary:
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 1Gi

readReplicas:
  enabled: false