apiVersion: v1
kind: ConfigMap
metadata:
  name: hw04-config
data:
  APP_PORT: "8000"
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-postgresql.database.svc.cluster.local:5432/maindb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"