apiVersion: v1
kind: Service
metadata:
  name: hw04-service
  labels:
    app: hw04-app
spec:
  selector:
    app: hw04-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP